In [ ]:
a = [
     [1, 2, 3], 
     [4, 5, 6]
     ]

a * 2


In [ ]:
# NumPy 설치 
!pip install numpy

In [7]:
import numpy 

a = [1, 2, 3, 4, 5, 6]
print("a: ", a)
print(type(a))

b = numpy.array(a)
print("b: ", b)
print(type(b))

a:  [1, 2, 3, 4, 5, 6]
<class 'list'>
b:  [1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
import numpy as np

np.array([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [10]:
np.array("d a t a e d u")

array('d a t a e d u', dtype='<U13')

In [11]:
np.arange(7) # range(7)

array([0, 1, 2, 3, 4, 5, 6])

In [12]:
np.arange(1, 6, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5])

In [16]:
# 파이썬 내장함수 range()
list(range(1, 6, 2))
# list(range(1, 6, 0.5))

[1, 3, 5]

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros([3, 2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
np.full(5, 3)

array([3, 3, 3, 3, 3])

In [23]:
np.full(5, 4).dtype


dtype('int64')

In [24]:
np.full(5, 4.).dtype

dtype('float64')

In [25]:
np.full(5, 4, dtype="float").dtype

dtype('float64')

In [26]:
# 2차원 배열

# 2행 5열
np.array([
    [1, 3, 5, 7, 9], 
    [2, 4, 6, 8, 10]
])

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [27]:
# 3행 3열
np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.ones((2, 5), dtype="int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [29]:
np.zeros((2, 5), dtype="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
np.full((2, 5), 5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [32]:
# 3차원배열

np.array([
    [
        [1, 2, 3, 4], 
        [5, 6, 7, 8]
    ], 
    [
        [2, 4, 6, 8], 
        [ 10, 12, 14, 16]
    ],
    [
        [1, 3, 5, 7], 
        [9, 11, 13, 15]
    ]
])

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 2,  4,  6,  8],
        [10, 12, 14, 16]],

       [[ 1,  3,  5,  7],
        [ 9, 11, 13, 15]]])

In [33]:
np.ones((3, 2, 4), dtype="int")

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [34]:
np.zeros((3, 2, 4), dtype="int")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [35]:
np.full((3, 2, 4), 5, dtype="int")

array([[[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]],

       [[5, 5, 5, 5],
        [5, 5, 5, 5]]])

In [37]:
# 1차원
arr_1d = np.array([1, 2, 3, 4])

# 2차원
arr_2d = np.array([
                    [1, 2, 3, 4], 
                    [5, 6, 7, 8]
                ])

# 3차원 
arr_3d = np.array([
                    [
                        [1, 2, 3, 4], 
                        [5, 6, 7, 8]
                    ], 
                    [
                        [2, 4, 6, 8], 
                        [10,12, 14, 16]
                    ], 
                    [
                        [1, 3, 5, 7], 
                        [9, 11, 13, 15]
                    ]
                ])

In [38]:
arr_1d.shape

(4,)

In [39]:
arr_2d.shape

(2, 4)

In [40]:
arr_3d.shape

(3, 2, 4)

In [41]:
arr_1d.size

4

In [42]:
arr_2d.size

8

In [43]:
arr_3d.size

24

In [44]:
arr_1d.ndim

1

In [45]:
arr_2d.ndim

2

In [46]:
arr_3d.ndim

3