In [1]:
import numpy as np 

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d[0]

np.int64(1)

In [3]:
print(arr_1d[0])

1


In [4]:
a = [1, 2, 3, 4, 5]
a[0]

1

In [5]:
print(arr_1d[2])

3


In [7]:
print(arr_1d[-1])

5


In [8]:
arr_2d = np.array([
                    [1, 2, 3], 
                    [4, 5, 7], 
                    [6, 8, 9],
                    [11, 17, 19]
])

In [12]:
print(arr_2d[0, 1])

2


In [13]:
print(arr_2d[-4, -3])

1


In [14]:
print(arr_2d[2, 1])

8


In [20]:
# 슬라이싱

arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d[0:2])
print(arr_1d[1:2])
print(arr_1d[:4])
print(arr_1d[1:])
print(arr_1d[:])


[1 2]
[2]
[1 2 3 4]
[2 3 4 5]
[1 2 3 4 5]


In [23]:
arr_2d = np.array([
            [1, 2, 3, 5], 
            [1, 3, 5, 7], 
            [2, 4, 6, 8], 
            [7, 11, 13, 17]
])

print(arr_2d[0:4])
print(arr_2d[0:4, 0])
print(arr_2d[0:4, 1])

[[ 1  2  3  5]
 [ 1  3  5  7]
 [ 2  4  6  8]
 [ 7 11 13 17]]
[1 1 2 7]
[ 2  3  4 11]


In [24]:
print(arr_2d[ :4, 0])

[1 1 2 7]


In [25]:
print(arr_2d[ : , 0])

[1 1 2 7]


In [26]:
arr_2d = np.array([
            [1, 2, 3, 5], 
            [1, 3, 5, 7], 
            [2, 4, 6, 8], 
            [7, 11, 13, 17]
])
print(arr_2d[0:3, 0:3])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [27]:
print(arr_2d[:3, :3])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [28]:
print(arr_2d[ :-1, :-1])

[[1 2 3]
 [1 3 5]
 [2 4 6]]
