In [1]:
import numpy as np 

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
arr_1d[0]

np.int64(1)

In [3]:
print(arr_1d[0])

1


In [4]:
a = [1, 2, 3, 4, 5]
a[0]

1

In [5]:
print(arr_1d[2])

3


In [7]:
print(arr_1d[-1])

5


In [8]:
arr_2d = np.array([
                    [1, 2, 3], 
                    [4, 5, 7], 
                    [6, 8, 9],
                    [11, 17, 19]
])

In [12]:
print(arr_2d[0, 1])

2


In [13]:
print(arr_2d[-4, -3])

1


In [14]:
print(arr_2d[2, 1])

8


In [20]:
# 슬라이싱

arr_1d = np.array([1, 2, 3, 4, 5])

print(arr_1d[0:2])
print(arr_1d[1:2])
print(arr_1d[:4])
print(arr_1d[1:])
print(arr_1d[:])


[1 2]
[2]
[1 2 3 4]
[2 3 4 5]
[1 2 3 4 5]


In [23]:
arr_2d = np.array([
            [1, 2, 3, 5], 
            [1, 3, 5, 7], 
            [2, 4, 6, 8], 
            [7, 11, 13, 17]
])

print(arr_2d[0:4])
print(arr_2d[0:4, 0])
print(arr_2d[0:4, 1])

[[ 1  2  3  5]
 [ 1  3  5  7]
 [ 2  4  6  8]
 [ 7 11 13 17]]
[1 1 2 7]
[ 2  3  4 11]


In [24]:
print(arr_2d[ :4, 0])

[1 1 2 7]


In [25]:
print(arr_2d[ : , 0])

[1 1 2 7]


In [26]:
arr_2d = np.array([
            [1, 2, 3, 5], 
            [1, 3, 5, 7], 
            [2, 4, 6, 8], 
            [7, 11, 13, 17]
])
print(arr_2d[0:3, 0:3])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [27]:
print(arr_2d[:3, :3])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [28]:
print(arr_2d[ :-1, :-1])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [29]:
arr_2d = np.array([
            [1, 2, 3, 5], 
            [1, 3, 5, 7], 
            [2, 4, 6, 8], 
            [7, 11, 13, 17]
])
type(arr_2d)


numpy.ndarray

In [30]:
print(arr_2d[1:3, 1:3 ])

[[3 5]
 [4 6]]


In [32]:
print(arr_2d[-3:-1, -3:-1])
print(arr_2d[1:-1, 1:-1])


[[3 5]
 [4 6]]
[[3 5]
 [4 6]]


In [34]:
print(arr_2d[1:3, 0:4])
print(arr_2d[1:3, :])
print(arr_2d[1:-1, :])

[[1 3 5 7]
 [2 4 6 8]]
[[1 3 5 7]
 [2 4 6 8]]
[[1 3 5 7]
 [2 4 6 8]]


In [37]:
arr_2d = np.array([
            [1, 2, 3, 5], 
            [1, 3, 5, 7], 
            [2, 4, 6, 8], 
            [7, 11, 13, 17]
])

print(arr_2d[3, 0:4])
print(arr_2d[3, :])
print(arr_2d[-1, :])

[ 7 11 13 17]
[ 7 11 13 17]
[ 7 11 13 17]


In [40]:
print(arr_2d[2:4, 2:4])
print(arr_2d[2:, 2:])
print(arr_2d[-2:, -2:])

[[ 6  8]
 [13 17]]
[[ 6  8]
 [13 17]]
[[ 6  8]
 [13 17]]


In [41]:
# ndarray 원소별 연산

arr = np.array([0, 1, -4, -16, 25])
print(arr)

[  0   1  -4 -16  25]


In [42]:
arr_abs = np.abs(arr)
print(arr_abs)

[ 0  1  4 16 25]


In [43]:
arr_fabs = np.fabs(arr)
print(arr_fabs)

[ 0.  1.  4. 16. 25.]


In [44]:
arr_sqrt = np.sqrt(arr)
print(arr)
print(arr_sqrt)

[  0   1  -4 -16  25]
[ 0.  1. nan nan  5.]


C:\Users\HRD영대\AppData\Local\Temp\ipykernel_5508\1085780605.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr_sqrt = np.sqrt(arr)


In [45]:
arr_square = np.square(arr)
print(arr)
print(arr_square)

[  0   1  -4 -16  25]
[  0   1  16 256 625]


In [46]:
arr_exp = np.exp(arr)
print(arr)
print(arr_exp)

[  0   1  -4 -16  25]
[1.00000000e+00 2.71828183e+00 1.83156389e-02 1.12535175e-07
 7.20048993e+10]


In [47]:
arr_log = np.log(arr)
print(arr)
print(arr_log)

[  0   1  -4 -16  25]
[      -inf 0.                nan        nan 3.21887582]


C:\Users\HRD영대\AppData\Local\Temp\ipykernel_5508\4217760339.py:1: RuntimeWarning: divide by zero encountered in log
  arr_log = np.log(arr)
C:\Users\HRD영대\AppData\Local\Temp\ipykernel_5508\4217760339.py:1: RuntimeWarning: invalid value encountered in log
  arr_log = np.log(arr)


In [48]:
arr_log10 = np.log10(arr)
print(arr)
print(arr_log10)

[  0   1  -4 -16  25]
[      -inf 0.                nan        nan 1.39794001]


C:\Users\HRD영대\AppData\Local\Temp\ipykernel_5508\784130791.py:1: RuntimeWarning: divide by zero encountered in log10
  arr_log10 = np.log10(arr)
C:\Users\HRD영대\AppData\Local\Temp\ipykernel_5508\784130791.py:1: RuntimeWarning: invalid value encountered in log10
  arr_log10 = np.log10(arr)


In [49]:
arr_sign = np.sign(arr)
print(arr)
print(arr_sign)

[  0   1  -4 -16  25]
[ 0  1 -1 -1  1]
